version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: inpad_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: inpad_user
      POSTGRES_PASSWORD: inpad_password
      POSTGRES_DB: inpad_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: