apiVersion: v1
kind: Secret
metadata:
  name: inpad-secrets
  namespace: inpad
type: Opaque
stringData:
  # PostgreSQL — учётные данные базы
  POSTGRES_USER: inpad_user
  POSTGRES_PASSWORD: inpad_password
  POSTGRES_DB: inpad_db

  # Строка подключения для бэкенда.
  # host = "postgres" — это имя сервиса БД внутри кластера (создадим следующим шагом)
  DATABASE_URL: "postgresql://inpad_user:inpad_password@postgres:5432/inpad_db"

  # Ключ для JWT-токенов
  JWT_SECRET: "super-secret-jwt-key-change-me"

  # MinIO — доступы к хранилищу файлов
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin

  # MySQL для WordPress
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: wordpress_password
  MYSQL_ROOT_PASSWORD: root_password
  WORDPRESS_URL: "http://wordpress:8080"
  WORDPRESS_USER: "admin"
  WORDPRESS_APP_PASSWORD: "TEoT rwWt NGzi I7wX pgv9 tdn8"